# Generated by Django 4.2.2 on 2023-06-23 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='identificador',
        ),
    ]
