# Generated by Django 4.2.2 on 2023-06-23 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_remove_servico_identificador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='protocole',
            new_name='protocolo',
        ),
    ]
